# set notification options
notifications: 
  email:
    recipients:
      - hou32hou@gmail.com
      - dheenodararao@gmail.com
    on_success: [always]
    on_failure: [always]

language: node_js # specify your language

cache: # cache node modules so that every build don't have to reinstall those node package again
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - ./scripts/transpile.sh
  - npm run build
  - npm test
