warnings_are_errors: false # So that travis don't treat warning as errors
# set notification options
notifications: 
  email:
    recipients:
      - hou32hou@gmail.com
      - dheenodararao@gmail.com
    on_success: always
    on_failure: always

language: node_js # specify your language

node_js: # specify version of node js
  - "6.11.3"

cache: # cache node modules so that every build don't have to reinstall those node package again
  directories:
    - "node_modules"

before_script:
  - sed -i "s/isProductionBuild = false/isProductionBuild = true/g" ./src/index.js # toggle production build to disable redux middleware
  - x=$(git log -1 --format=%aI)
  - sed -i "s/TIMESTAMP/$x/g" ./public/index.html

script:
  - echo "Running script:"
  - ./scripts/transpile
  - npm test
  - ./scripts/upload-coverage-report
  - rm -rf  ./src/core/tests/ # remove test data which is not needed in production build
  - cp modifiedNodeModules/phin.js node_modules/phin/lib/phin.js # use ES5 phin.js because the original one cannot be minified properly
  - npm run build

after_script:
  - echo "script finished."

after_success: # upload source-analysis-report
  - source-map-explorer --html build/static/js/main.* > source_analysis/index.html
  - surge -d ttap-source-analysis.surge.sh -p ./source_analysis/

deploy:
  provider: surge
  project: ./build/
  domain: https://ttap.surge.sh  
  skip_cleanup: true
