# set notification options
notifications: 
  email:
    recipients:
      - hou32hou@gmail.com
      - dheenodararao@gmail.com
    on_success: always
    on_failure: always

language: node_js # specify your language

node_js: # specify version of node js
  - "6.11.3"

cache: # cache node modules so that every build don't have to reinstall those node package again
  directories:
    - "node_modules"


script:
  - echo "Running script:"
  - ./scripts/transpile.sh
  - npm run build
  - npm test

after_script:
  - echo "script finished."

after_success:
  - npm run deploy