warnings_are_errors: false # So that travis don't treat warning as errors
# set notification options
notifications: 
  email:
    recipients:
      - hou32hou@gmail.com
      - dheenodararao@gmail.com
    on_success: always
    on_failure: always

language: node_js # specify your language

node_js: # specify version of node js
  - "6.11.3"

cache: # cache node modules so that every build don't have to reinstall those node package again
  directories:
    - "node_modules"

before_script:
  - sed -i "s/API_KEY/$firebase/g" ./ts/fire.ts # inject firebase API
  - sed -i "s/isProductionBuild = false/isProductionBuild = true/g" ./src/index.js # toggle production build to disable redux middleware
  - sed -i "s/polyfill/polyfill --coverage/g" ./package.json #Add --coverage option for running test

script:
  - echo "Running script:"
  - ./scripts/transpile
  - npm run build
  - npm test

after_script:
  - echo "script finished."

deploy:
  provider: surge
  project: ./build/
  domain: https://ttap.surge.sh  
  skip_cleanup: true
